apiVersion: v1
kind: Service
metadata:
  name: finsight-api-service
  namespace: default
spec:
  selector:
    app: finsight-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP