apiVersion: v1
kind: Service
metadata:
  name: finsight-nginx-service
  namespace: default
spec:
  selector:
    app: finsight-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer